### ISSUE TITLE
Перевод rust by example

### ISSUE THREAD

**Issue by Gordon-F** [rust-lang-ru/rust-by-example-ru#1]
- [x] Introduction
- [x] 1. Hello World 
  - [x] 1.1. Comments
  - [x] 1.2. Formatted print
    - [x] 1.2.1. Debug
    - [x] 1.2.2. Display
      - [x] 1.2.2.1. Testcase: List
    - [x] 1.2.3. Formatting
- [x] 2. Primitives
  - [x] 2.1. Literals and operators
  - [x] 2.2. Tuples
  - [x] 2.3. Arrays and Slices
- [x] 3. Custom types
  - [x] 3.1. Structures
  - [x] 3.2. Enums
    - [x] 3.2.1. use
    - [x] 3.2.2. C-like
    - [x] 3.2.3. Testcase: linked-list
  - [x] 3.3. constants
- [x] 4. Variable Bindings
  - [x] 4.1. Mutability
  - [x] 4.2. Scope and shadowing
  - [x] 4.3. Declare first
- [x] 5. Casting
  - [x] 5.1. Literals
  - [x] 5.2. Inference
  - [x] 5.3. Alias
- [x] 6. Expressions
- [x] 7. Flow Control
  - [x] 7.1. if/else
  - [x] 7.2. loop
    - [x] 7.2.1. Nesting and labels
  - [x] 7.3. while
  - [x] 7.4. for and range
  - [x] 7.5. match
    - [x] 7.5.1. Destructuring
      - [x] 7.5.1.1. tuples
      - [x] 7.5.1.2. enums
      - [x] 7.5.1.3. pointers/ref
      - [x] 7.5.1.4. structs
    - [x] 7.5.2. Guards
    - [x] 7.5.3. Binding
  - [x] 7.6. if let
  - [x] 7.7. while let
- [x] 8. Functions
  - [x] 8.1. Methods
  - [x] 8.2. Closures
    - [x] 8.2.1. Capturing
    - [x] 8.2.2. As input parameters
    - [x] 8.2.3. Type anonymity
    - [x] 8.2.4. Input functions
    - [x] 8.2.5. As output parameters
    - [x] 8.2.6. Examples in `std`
      - [x] 8.2.6.1. Iterator::any
      - [x] 8.2.6.2. Iterator::find
  - [x] 8.3. Higher Order Functions
- [x] 9. Modules
  - [x] 9.1. Visibility
  - [x] 9.2. Struct visibility
  - [x] 9.3. The `use` declaration
  - [x] 9.4. `super` and `self`
  - [x] 9.5. File hierarchy
- [x] 10. Crates
  - [x] 10.1. Library
  - [x] 10.2. `extern crate`
- [x] 11. Attributes
  - [x] 11.1. `dead_code`
  - [x] 11.2. Crates
  - [x] 11.3. `cfg`
    - [x] 11.3.1. Custom
- [x] 12. Generics
  - [x] 12.1. Functions
  - [x] 12.2. Implementation
  - [ ] 12.3. Traits
  - [ ] 12.4. Bounds
    - [ ] 12.4.1. Testcase: empty bounds
  - [ ] 12.5. Multiple bounds
  - [ ] 12.6. Where clauses
  - [ ] 12.7. Associated items
    - [ ] 12.7.1. The Problem
    - [ ] 12.7.2. Associated types
  - [ ] 12.8. Phantom type parameters
    - [ ] 12.8.1. Testcase: unit clarification
- [ ] 13. Scoping rules
  - [x] 13.1. RAII
  - [x] 13.2. Ownership and moves
  - [x] 13.2.1. Mutability
  - [x] 13.3. Borrowing
    - [ ] 13.3.1. Mutability
    - [x] 13.3.2. Freezing
    - [ ] 13.3.3. Aliasing
    - [ ] 13.3.4. The ref pattern
  - [ ] 13.4. Lifetimes
    - [ ] 13.4.1. Explicit annotation
    - [ ] 13.4.2. Functions
    - [x] 13.4.3. Methods
    - [x] 13.4.4. Structs
    - [ ] 13.4.5. Bounds
    - [ ] 13.4.6. Coercion
    - [ ] 13.4.7. static
    - [ ] 13.4.8. elision
- [x] 14. Traits
  - [x] 14.1. Derive
  - [x] 14.2. Operator Overloading
  - [x] 14.3. Drop
  - [ ] 14.4. Iterators
  - [ ] 14.5. Clone
- [x] 15. macro_rules!
  - [ ] 15.1. Designators
  - [ ] 15.2. Overload
  - [ ] 15.3. Repeat
  - [ ] 15.4. DRY (Don't Repeat Yourself)
- [x] 16. Error handling
  - [ ] 16.1. Option & unwrap
  - [ ] 16.2. map
  - [ ] 16.3. and_then
  - [ ] 16.4. Result
    - [ ] 16.4.1. map for Result
    - [ ] 16.4.2. aliases for Result
  - [ ] 16.5. Options with Results
    - [ ] 16.5.1. Strings as errors
    - [ ] 16.5.2. Combining separate combinators
    - [ ] 16.5.3. Enter try!
  - [ ] 16.6. The limits of strings
  - [ ] 16.7. Re-enter try!
  - [ ] 16.8. Re-enabling box
- [ ] 17. Std library types
  - [x] 17.1. Box, stack and heap
  - [x] 17.2. Vectors
  - [ ] 17.3. Strings
  - [x] 17.4. `Option`
  - [ ] 17.5. `Result`
    - [ ] 17.5.1. `try!`
  - [x] 17.6. `panic!`
  - [ ] 17.7. HashMap
    - [ ] 17.7.1. Alternate/custom key types
    - [ ] 17.7.2. HashSet
- [x] 18. Std misc
  - [x] 18.1. Threads
  - [ ] 18.2. Channels
  - [ ] 18.3. Path
  - [ ] 18.4. File I/O
  - [ ] 18.4.1. `open`
  - [ ] 18.4.2. `create`
  - [ ] 18.5. Child processes
    - [ ] 18.5.1. Pipes
    - [ ] 18.5.2. Wait
  - [ ] 18.6. Filesystem Operations
  - [ ] 18.7. Program arguments
    - [ ] 18.7.1. Argument parsing
  - [ ] 18.8. Foreign Function Interface
- [ ] 19. Meta
  - [ ] 19.1. Documentation
  - [ ] 19.2. Testing
- [ ] 20. Unsafe operations

**Comment by webmstk** [comment]
надо обновить )

**Comment by andreevlex** [comment]
https://github.com/rust-lang-ru/community/issues/42

Перевод ведётся в репозитории https://github.com/rust-lang-ru/rust-by-example.
