### ISSUE TITLE
Невидимые элементы (отсутствуют картинки)

### ISSUE THREAD

**Issue by karavzeka** [rust-lang-ru/rust-by-example-ru#120]
Невидимы кнопки: меню, смена темы, печать, следующая страница, предыдущая страница.

Так же невидимы кнопки в блоках кода: _Undo changes_, _Copy to clipboard_, _Run this code_. На них не удается нажать.

**Comment by karavzeka** [comment]
![a191e68fe1](https://user-images.githubusercontent.com/5681854/39983012-dcaa8e36-575e-11e8-961a-e0f777513ca9.jpg)

**Comment by andreevlex** [comment]
Сейчас буду собирать локально и смотреть что не так.

**Comment by andreevlex** [comment]
Локально все нормально, картинки есть. хм хм.

**Comment by andreevlex** [comment]
переключился на `gh-pages`, скачал локально.
Все работает.
переименовал  - `_FontAwesome` в `_FontAwesome_` и все сломалось.
Не видит каталога со стилями в итоге.

**Comment by andreevlex** [comment]
Вот где собака зарыта оказывается.
https://github.com/rust-lang-nursery/mdBook/commit/f01bf88e69cf84fb253962f5d78b7c5a4eaf8306
https://github.com/rust-lang-nursery/mdBook/commit/f01bf88e69cf84fb253962f5d78b7c5a4eaf8306#diff-9f0d373829e789d9a6923dd290c5b174L21

В оригинале идет ссылка на стили https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css, а потом ее грохнули.

Прикол в том, что по адресу https://doc.rust-lang.org/stable/rust-by-example/ лежат файлы со ссылками на https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css, а `gh-pages` ссылками на _FontAwesome/css/font-awesome.css

=)

**Comment by andreevlex** [comment]
@karavzeka кнопки и навигация в наличии!
Ждем когда исправят оригинал.

**Comment by karavzeka** [comment]
@andreevlex Здорово!
Я правильно понял, что таск закрываем после исправления оригинала?

**Comment by andreevlex** [comment]
https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/ вот тут еще документация github почему так.

И это исправили https://github.com/rust-lang-nursery/mdBook/pull/697

**Comment by andreevlex** [comment]
Так чего -то все опять сломалось...
Они этот фикс не отправили на https://crates.io/crates/mdbook
!!!

**Comment by andreevlex** [comment]
https://github.com/rust-lang-ru/community/issues/42

Перевод ведётся в репозитории https://github.com/rust-lang-ru/rust-by-example.
