### ISSUE TITLE
Поиск включается не в тему

### ISSUE THREAD

**Issue by denvolj** [rust-lang-ru/rust-by-example-ru#130]
Если нажать 's' во время редактирования кода, то открывается поиск.

ОС: Ubuntu 
Версия: 18.04
Разрядность: 64-bit

Браузер: Mozilla Firefox Quantum 
Версия: 63.0.3 
Разрядность: 64-bit

**Comment by andreevlex** [comment]
https://github.com/rust-lang-ru/community/issues/42

Перевод ведётся в репозитории https://github.com/rust-lang-ru/rust-by-example.
