### ISSUE TITLE
Добавить ссылки на русскоязычные источники

### ISSUE THREAD

**Issue by Gordon-F** [rust-lang-ru/rust-by-example-ru#2]
В блоки "Смотрите также" можно добавить ссылки на русскоязые источники по Rust. Можно на [перевод книги](http://rurust.github.io/rust_book_ru/) или на переведенные статьи на хабре.

**Comment by vessd** [comment]
С официального сайта есть ссылка на https://github.com/ctjhoa/rust-learning#locale-links
Соответственно лучше ссылки пушить сюда https://github.com/ctjhoa/rust-learning/blob/master/ru_RU.md

**Comment by Gordon-F** [comment]
@vessd Я хотел рядом со ссылками на оригинальную книгу и документацию добавлять ссылку на русскоязычную книгу (статью и т.д)

**Comment by vessd** [comment]
Пока не понял твою мысль

**Comment by Gordon-F** [comment]
@vessd Например, на этой странице https://rurust.github.io/rust-by-example-ru/custom_types/structs.html в блоке "Смотрите также" должна быть ссылка на http://rurust.github.io/rust_book_ru/src/structs.html

**Comment by andreevlex** [comment]
https://github.com/rust-lang-ru/community/issues/42

Перевод ведётся в репозитории https://github.com/rust-lang-ru/rust-by-example.
