### ISSUE TITLE
Добавить кнопку "Изменить пример" на страницах с примерами

### ISSUE THREAD

**Issue by Gordon-F** [rust-lang-ru/rust-by-example-ru#20]
Стоит ли добавлять на каждую страницу с примерами кнопки (ссылку?) "Изменить пример" и "Изменить исходный код примера" ? Которые будут открывать редактор гитхаба для соответствующих страниц.

По аналогии с "Предложить правки" на rustycrate.ru.

**Comment by mkpankov** [comment]
Там ведь есть кнопка запуска примера, зачем нужно ещё что-то?

**Comment by Gordon-F** [comment]
@mkpankov Кнопка (ссылка) для внесения изменений в исходный код примера, исходного кода примера, сразу через редактор гитхаба.

**Comment by vessd** [comment]
Идея в принципе не плоха, но ещё раз осмотрев интерфейс я так и не смог решить куда её поместить.
Возможно нам всё же стоит обойтись достаточно подробной инструкцией.

**Comment by mkpankov** [comment]
Так всё-таки, "изменить пример" или "изменить страницу"? Причём здесь пример? Я понял "пример" как "код примера".

**Comment by Gordon-F** [comment]
@mkpankov дело все в том, что сама страница в исходном коде находится чаще всего в двух файлах:

1. Текст - md файл.
2. Исходный код примера - .rs файл.

"Изменить пример" - ссылка на текст. md файл. "Изменить исходный код примера" - ссылка на .rs файла.

**Comment by andreevlex** [comment]
https://github.com/rust-lang-ru/community/issues/42

Перевод ведётся в репозитории https://github.com/rust-lang-ru/rust-by-example.
