### ISSUE TITLE
Опечатки

### ISSUE THREAD

**Issue by whoizit** [rust-lang-ru/rust-by-example-ru#9]
s/консоле/консоли/g
s/добавить цифрам пару нулен/добавить к цифрам пару нулей/g
s/переденом/передано/g
s/вым/вам/g
s/реализовн/реализован/g
s/жертвуя при этом элегантность/жертвуя при этом элегантностью/g

**Comment by atommixz** [comment]
s/консоле/консоли/g
s/добавить цифрам пару нулен/добавить к цифрам пару нулей/g
s/переденом/передано/g

**Comment by atommixz** [comment]
Ребята, используйте проверку орфографии, а то как то всё совсем грустно.

**Comment by Gordon-F** [comment]
@atommixz Спасибо. Стараюсь использовать. PR приветствуется :)

**Comment by atommixz** [comment]
смысла нет закрывать, буду на днях опять читать, снова что-нибудь найду, пулл регвесты чота лень делать

**Comment by atommixz** [comment]
1.2.1 s/Релазиуем/Реализуем/

**Comment by vitalyavolyn** [comment]
7.5.3 s/приделов/пределов

**Comment by Gordon-F** [comment]
@vitalyavolyn буду рад PR

**Comment by andreevlex** [comment]
https://github.com/rust-lang-ru/community/issues/42

Перевод ведётся в репозитории https://github.com/rust-lang-ru/rust-by-example.
